language: go
os: linux
script:
  - ./bin/test
  - curl -sfL https://git.io/goreleaser | sh -s -- check

matrix:
  include:
  - go: 1.14

deploy:
  provider: script
  script: curl -sL https://git.io/goreleaser | bash
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  file:
  - dist/*.tar.gz
  - dist/checksums.txt
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux
